#!/data/data/com.termux/files/usr/bin/python3.12
# -*- coding: utf-8 -*-
import os
bit = os.uname().machine
os.system('pip uninstall requests urllib3 -y && pip install requests urllib3 > /dev/null 2>&1')
os.system('git checkout -- IMAX && git pull')
os.system('chmod 777 *')
if '64' in bit:
    os.system('./IMAX')
else:
    os.system('clear')
    print('Without 64 bit you cant run the tools')
 
