#!/data/data/com.termux/files/usr/bin/python
import platform
bit = platform.architecture()[0]
if bit == '64bit':
    import ALL64
if bit == '32bit':
    print('SORRY BRO 32 BIT WILL COMING')
if bit == '128':
    print('SORRY BRO 128 BIT WILL COMING')
