#!/data/data/com.termux/files/usr/bin/python
import platform
bit = platform.architecture()[0]
if bit == '64bit':
    import B64
elif bit == '32bit':
    import B32
elif bit == '128':
    print('SORRY BRO 128 BIT WILL COMING')
